# Generated by Django 4.2.11 on 2026-01-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('PESQUISA', 'Pesquisa'), ('CIENTIFICO', 'Científico'), ('TCC', 'TCC')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDANT', 'Pendente'), ('PUBLISHED', 'Publicado'), ('REFUSED', 'Reprovado')], max_length=20)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(related_name='projects', to='authentication.user')),
                ('tags', models.ManyToManyField(related_name='projects', to='project.tag')),
            ],
        ),
    ]
