# Generated by Django 5.2.7 on 2026-01-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='projects/banners/'),
        ),
    ]
