# Generated by Django 5.2.7 on 2026-01-26 00:50

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalsolicitation',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='approvalsolicitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=project.models.project_image_path),
        ),
    ]
