# Generated by Django 4.2.11 on 2026-01-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('PESQUISA', 'Pesquisa'), ('INTEGRADOR', 'Integrador'), ('TCC', 'TCC')], max_length=20),
        ),
    ]
