# Generated by Django 5.2.7 on 2026-01-25 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='project.course'),
        ),
    ]
