# Generated by Django 5.2.7 on 2026-01-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_approvalsolicitation_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Em Andamento'), ('completed', 'Concluído')], default='pending_approval', max_length=20),
        ),
    ]
