# Generated by Django 5.2.7 on 2026-01-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pendente de Aprovação'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído'), ('reproved', 'Reprovado')], default='pending_approval', max_length=20),
        ),
    ]
