# Generated by Django 5.2.7 on 2026-01-26 15:27

import ckeditor.fields
import django.db.models.deletion
import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalsolicitation',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='project',
            name='banner',
        ),
        migrations.AddField(
            model_name='approvalsolicitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=project.models.project_image_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='project.course'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
