# Generated by Django 4.2.11 on 2026-01-02 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('project', '0002_alter_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='guiding_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guided_projects', to='authentication.user'),
        ),
    ]
