# Generated by Django 5.2.7 on 2026-01-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pendente de Aprovação'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído')], default='pending_approval', max_length=20),
        ),
    ]
