# Generated by Django 4.2.11 on 2026-01-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_guiding_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PENDANT', 'Pendente'), ('Publicado', 'Publicado'), ('REFUSED', 'Reprovado')], max_length=20),
        ),
    ]
