# Generated by Django 5.2.7 on 2026-01-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalsolicitation',
            name='type',
            field=models.CharField(choices=[('creation', 'Criação de Projeto'), ('correction', 'Correção de Projeto')], default='creation', max_length=20),
        ),
    ]
