# Generated by Django 5.2.7 on 2026-01-26 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_approvalsolicitation_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('acronym', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campus/photos/')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campi',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='institution',
        ),
        migrations.AddField(
            model_name='course',
            name='campus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='project.campus'),
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
