# Generated by Django 4.2.11 on 2026-01-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PENDANT', 'Pendente'), ('APPROVED', 'Aprovado'), ('REFUSED', 'Reprovado')], max_length=20),
        ),
    ]
