# Generated by Django 4.2.11 on 2026-01-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Pendente', 'Pendente'), ('Reprovado', 'Reprovado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('PESQUISA', 'Pesquisa'), ('Integrador', 'Integrador'), ('TCC', 'TCC')], max_length=20),
        ),
    ]
