# Generated by Django 4.2.11 on 2026-01-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_project_status_alter_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Pesquisa', 'PESQUISA'), ('Integrador', 'INTEGRADOR'), ('TCC', 'TCC')], max_length=20),
        ),
    ]
